### ISSUE TITLE
Query plan RPC

### ISSUE THREAD

**Issue by smburdick** [Puget-Sound-Bitmaps/distributed-system#31]
Query plans are returned by different algorithms. IterPrim's returns a list of `(root, tree)` tuples, where `tree` is a `Int -> Vertex` mapping and each `Vertex` contains a list of vectors and a list of integers that you use as keys in `tree` as before. This can be reworked to just be nodes that have `Node` objects of the same type as children, *if* we want every algorithm to follow the same interface (which is probably a good idea).
The input to the initiate-query RPC will be
```RPC
struct query_args {
    struct query_args *recur_query_list; 
    vec_t local_vectors[];
    char local_ops[];
    char subquery_ops[];
    string this_machine_address;
}
```
I'm writing out the code for the actual RPC. I can see how `local_ops` is used for the base case, but how `subquery_ops` are used in conjunction with the query results, I'm not exactly certain of. @Jahrme can you provide a few lines of pseudocode for this RPC?

**Comment by Jahrme** [comment]
Here is what I am thinking the process would look like, written in pseudo-python.
```python
def query(args):
    local_vectors = []

    # Grab each local vector, could be done in parallel
    for vec in args.local_vectors:
        local_vectors.append(get_vector(vec))

    result = local_vectors.pop()

    while local_vectors:
        operator = args.local_ops.pop()
        second_vec = local_vectors.pop()

        if operator is AND:
            result = result.WAH_AND(second_vec)

        elif operator is OR:
            result = result.WAH_OR(second_vec)

        else:
            exit("Invalid operator")

    subquery_results = []

    # Perform each subquery, could be done in parallel
    for subquery in args.recur_query_list:
        subquery_result = query(subquery)
        subquery_results.append(subquery_result)

    # result still holds the full local results which we build off of

    while subquery_results:
        operator = args.subquery_ops.pop()
        second_vec = subquery_results.pop()

        if operator is AND:
            result = result.WAH_AND(second_vec)

        elif operator is OR:
            result = result.WAH_OR(second_vec)

        else:
            exit("Invalid operator")

    return result
```
